Partial views, Load more/Controllers/AccessoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Partial_views__Load_more.Data;
using Partial_views__Load_more.Models;
using Partial_views__Load_more.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Partial_views__Load_more.Controllers
{
    public class AccessoriesController : Controller
    {
        private readonly AppDbContext _context;
        public AccessoriesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.count = await _context.Products.Where(m => !m.IsDeleted).CountAsync();

            IEnumerable <Product> products = await _context.Products.Where(m => !m.IsDeleted).Take(3).ToListAsync();

            return View(products);
        }

        public async Task<IActionResult> LoadMore(int skip)
        {
            IEnumerable<Product> products = await _context.Products.Where(m => !m.IsDeleted).Skip(skip).Take(3).ToListAsync();

            return PartialView("_ProductsPartial", products);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null) return BadRequest();

            var dbProduct = await GetProductById(id);

            if (dbProduct == null) return NotFound();

            List<BasketVM> basket = GetBasket();

            UpdateBasket(basket, dbProduct.Id);

            Response.Cookies.Append("basket", JsonConvert.SerializeObject(basket));

            return RedirectToAction(nameof(Index));
        }

        private void UpdateBasket(List<BasketVM> basket, int id)
        {
            BasketVM existProduct = basket.FirstOrDefault(m => m.Id == id);

            if (existProduct == null)
            {
                basket.Add(new BasketVM
                {
                    Id = id,
                    Count = 1
                });
            }
            else
            {
                existProduct.Count++;
            }
        }

        private async Task<Product> GetProductById(int? id)
        {
            return await _context.Products.FindAsync(id);
        }

        private List<BasketVM> GetBasket()
        {
            List<BasketVM> basket;

            if (Request.Cookies["basket"] != null)
            {
                basket = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["basket"]);
            }
            else
            {
                basket = new List<BasketVM>();
            }

            return basket;
        }
    }
}

Partial views, Load more/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<Product>

@foreach (var product in Model)
{
    <div class="col-lg-4 col-md-6 col-sm-12">
        <div product-id="1" class="card my-card" style="width: 18rem;">
            <div class="image">
                <i class="fa-solid fa-heart"></i>
                <img src="~/assets/images/accessories/@product.Image" class="card-img-top"
                     alt="...">
            </div>
            <div class="card-body card-bottom">
                @*<div class="add-product">
                        <a href="">
                            <i class="fa-solid fa-cart-shopping"></i>
                        </a>
                    </div>*@
                <form asp-controller="Accessories" asp-action="AddBasket" asp-route-id="@product.Id" method="post">
                    <button type="submit" class="btn btn-primary">add to cart</button>
                </form>
                <h5 class="card-title">@product.Title</h5>
                <h6 class="card-text">$ @product.Price</h6>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star-half-sharp"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
            </div>
        </div>
    </div>
}